service: aws-serverless-registration-app

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    usePipenv: false
    invalidateCaches: true
    strip: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
        - "**/*.pyc"
        - "**/*.pyo"
        - "**/__pycache__*"

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  deploymentMethod: direct
  runtime: python3.9
  stage: dev
  httpApi:
    cors: true
    disableDefaultEndpoint: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:345218099459:table/levelup*
            - arn:aws:dynamodb:${self:provider.region}:345218099459:table/levelup*/index/*
  environment:
    # https://www.serverless.com/blog/aws-secrets-management/
    SECRET_KEY: ${ssm:/FLASK_SECRET_KEY}

functions:
  api:
    handler: wsgi_handler.handler
    description: Level Up web-app & interactive API endpoints
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - '!node_modules/**'
    - '!package.*'
    - '!Pipfile*'
    - '!static/**'
    - '!*.md'
    - '!Makefile'
    - '!.venv'
    - '!dist'
    - '!docker'
    - '!docker*.*'
    - 'templates/**'

